src/InfinityCinema/Web/InfinityCinema.Web/Areas/Administration/Controllers/DashboardController.cs
namespace InfinityCinema.Web.Areas.Administration.Controllers
{
    using InfinityCinema.Web.Areas.Administration.AdministartionsService;
    using Microsoft.AspNetCore.Mvc;

    public class DashboardController : AdministrationController
    {
        private readonly IAdministartionService administartionService;

        public DashboardController(IAdministartionService administartionService)
        {
            this.administartionService = administartionService;
        }

        public IActionResult Statistics()
        {
            return this.View(this.administartionService.ApplicationStatistics());
        }
    }
}

src/InfinityCinema/Web/InfinityCinema.Web/Controllers/ActorsController.cs
namespace InfinityCinema.Web.Controllers
{
    using System.Threading.Tasks;
    using System.Web.Http;

    using InfinityCinema.Common;
    using InfinityCinema.Services.Data.ActorsService;
    using InfinityCinema.Services.Data.ActorsService.Models;
    using InfinityCinema.Services.Data.MovieActorsService;
    using InfinityCinema.Services.Data.MoviesService;
    using Microsoft.AspNetCore.Mvc;

    using HttpPostAttribute = System.Web.Http.HttpPostAttribute;

    public class ActorsController : BaseController
    {
        private readonly IActorService actorService;
        private readonly IMovieActorService movieActorService;

        public ActorsController(IActorService actorService, IMovieActorService movieActorService)
        {
            this.actorService = actorService;
            this.movieActorService = movieActorService;
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public async Task<IActionResult> DeleteAsync(int actorId, int movieId)
        {
            await this.movieActorService.RemoveRelationBetweenMovieActorsAndActosTablesAsync(actorId, movieId);
            await this.actorService.DeleteAsync(actorId);

            return this.RedirectToAction("EditMovieActors", "Movies", new { movieId = movieId });
        }

        [HttpPost]
        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public async Task<IActionResult> CreateAsync(ActorFormModel actorForm)
        {
            if (!this.ModelState.IsValid)
            {
                return this.RedirectToAction("EditMovieActors", "Movies", new { movieId = actorForm.MovieId, newActor = actorForm });
            }

            ActorViewModel actor = this.actorService.GetActorByNames(actorForm.FullName);

            if (actor == null)
            {
                actor = await this.actorService.CreateAsync<ActorViewModel>(actorForm);
            }

            await this.actorService.CreateRowForMappingTableMovieActorsAsync(actorForm.MovieId, actor.Id);

            return this.RedirectToAction("EditMovieActors", "Movies", new { movieId = actorForm.MovieId });
        }
    }
}

src/InfinityCinema/Web/InfinityCinema.Web/Controllers/GenresController.cs
namespace InfinityCinema.Web.Controllers
{
    using System.Collections.Generic;

    using InfinityCinema.Services.Data.GenresService;
    using InfinityCinema.Services.Data.GenresService.Models;
    using Microsoft.AspNetCore.Mvc;

    public class GenresController : BaseController
    {
        private readonly IGenreService genreService;

        public GenresController(IGenreService genreService)
        {
            this.genreService = genreService;
        }

        [HttpGet]
        public IActionResult All(string searchName = null)
        {
            IEnumerable<GenreViewModel> genres = this.genreService.All<GenreViewModel>(searchName);

            return this.View(genres);
        }
    }
}

src/InfinityCinema/Web/InfinityCinema.Web/Controllers/ImagesController.cs
namespace InfinityCinema.Web.Controllers
{
    using System.Threading.Tasks;

    using InfinityCinema.Common;
    using InfinityCinema.Services.Data.ImagesService;
    using InfinityCinema.Services.Data.ImagesService.Models;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    public class ImagesController : BaseController
    {
        private readonly IImageService imageService;

        public ImagesController(IImageService imageService)
        {
            this.imageService = imageService;
        }

        [HttpGet]
        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public async Task<IActionResult> DeleteAsync(int imageId, int movieId)
        {
            await this.imageService.DeleteAsync(imageId);

            return this.RedirectToAction("EditMovieImages", "Movies", new { movieId = movieId });
        }

        [HttpPost]
        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public async Task<IActionResult> CreateAsync(ImageFormModel imageForm)
        {
            if (!this.ModelState.IsValid)
            {
                return this.RedirectToAction("EditMovieImages", "Movies", new { movieId = imageForm.MovieId, newImage = imageForm });
            }

            await this.imageService.CreateAsync<ImageViewModel>(imageForm);

            return this.RedirectToAction("EditMovieImages", "Movies", new { movieId = imageForm.MovieId });
        }
    }
}

src/InfinityCinema/Web/InfinityCinema.Web/Controllers/PlatformsController.cs
namespace InfinityCinema.Web.Controllers
{
    using System.Threading.Tasks;

    using InfinityCinema.Common;
    using InfinityCinema.Services.Data.MoviePlatformsService;
    using InfinityCinema.Services.Data.PlatformsService;
    using InfinityCinema.Services.Data.PlatformsService.Models;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    public class PlatformsController : BaseController
    {
        private readonly IPlatformService platformService;
        private readonly IMoviePlatformService moviePlatformService;

        public PlatformsController(IPlatformService platformService, IMoviePlatformService moviePlatformService)
        {
            this.platformService = platformService;
            this.moviePlatformService = moviePlatformService;
        }

        [HttpPost]
        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public async Task<IActionResult> DeleteAsync(int platformId, int movieId)
        {
            await this.moviePlatformService.RemoveRelationBetweenMoviePlatformsAndPlatformsTablesAsync(platformId, movieId);

            await this.platformService.DeleteAsync(platformId);

            return this.RedirectToAction("EditMoviePlatforms", "Movies", new { movieId = movieId });
        }

        [HttpPost]
        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public async Task<IActionResult> CreateAsync(PlatformFormModel platformForm)
        {
            if (!this.ModelState.IsValid)
            {
                return this.RedirectToAction("EditMoviePlatforms", "Movies", new { newPlatform = platformForm, movieId = platformForm.MovieId });
            }

            PlatformViewModel platform = this.platformService.GetViewModelByName<PlatformViewModel>(platformForm.Name);

            if (platform == null)
            {
                platform = await this.platformService.CreateAsync<PlatformViewModel>(platformForm);
            }

            await this.moviePlatformService.CreateRowForMappingTableMoviePlatformsAsync(platformForm.MovieId, platform.Id);

            return this.RedirectToAction("EditMoviePlatforms", "Movies", new { movieId = platformForm.MovieId });
        }
    }
}

src/InfinityCinema/Web/InfinityCinema.Web/Areas/Administration/Views/Dashboard/Statistics.cshtml
@model AdministartionIndexViewModel

@{
    this.ViewData["Title"] = "Admin dashboard";
}

<div class="container mb-5">
    <center>
        <h1 class="text-center mt-5">@this.ViewData["Title"]</h1>
    </center>
    <div class="jumbotron mt-5">
        <div class="container">
            <div class="row">
                <span class="badge badge-warning offset-1 col-2">Movies: @Model.TotalMovies</span>
                <span class="badge badge-warning offset-2 col-2">Genres: @Model.TotalGenres</span>
                <span class="badge badge-warning offset-2 col-2">Users: @Model.TotalUsers</span>
            </div>
        </div>
        <div class="mt-5"></div>
        <hr class="my-4">
        <div class="mb-5"></div>
        <p class="lead">
            <h4 class="mb-3">| Create:</h4>
            <div class="row mb-4">
                <a asp-area="Administration" asp-controller="Movies" asp-action="Create" class="btn btn-warning col-2 rounded-pill">Crate Movie</a>
                <a asp-area="Administration" asp-controller="Actors" asp-action="Create" class="btn btn-warning offset-1 col-2 rounded-pill">Create Actor</a>
                <a asp-area="Administration" asp-controller="Genres" asp-action="Create" class="btn btn-warning offset-1 col-2 rounded-pill">Create Genre</a>
                <a asp-area="Administration" asp-controller="Images" asp-action="Create" class="btn btn-warning offset-1 col-2 rounded-pill">Create Image</a>
            </div>
            <div class="row mb-5">
                <a asp-area="Administration" asp-controller="Directors" asp-action="Create" class="btn btn-warning col-2 rounded-pill">Create Director</a>
                <a asp-area="Administration" asp-controller="Platforms" asp-action="Create" class="btn btn-warning offset-1 col-2 rounded-pill">Create Platform</a>
                <a asp-area="Administration" asp-controller="Languages" asp-action="Create" class="btn btn-warning offset-1 col-2 rounded-pill">Create Language</a>
                <a asp-area="Administration" asp-controller="Countries" asp-action="Create" class="btn btn-warning offset-1 col-2 rounded-pill">Create Country</a>
            </div>
        </p>
        <p class="lead">
            <h4 class="mb-3">| Read:</h4>
            <div class="row mb-4">
                <a asp-area="Administration" asp-controller="Movies" asp-action="Index" class="btn btn-warning col-2 rounded-pill">View All Movies</a>
                <a asp-area="Administration" asp-controller="Actors" asp-action="Index" class="btn btn-warning offset-1 col-2 rounded-pill">View All Actors</a>
                <a asp-area="Administration" asp-controller="Genres" asp-action="Index" class="btn btn-warning offset-1 col-2 rounded-pill">View All Genres</a>
                <a asp-area="Administration" asp-controller="Images" asp-action="Index" class="btn btn-warning offset-1 col-2 rounded-pill">View All Images</a>
            </div>
            <div class="row mb-5">
                <a asp-area="Administration" asp-controller="Directors" asp-action="Index" class="btn btn-warning col-2 rounded-pill">View All Directors</a>
                <a asp-area="Administration" asp-controller="Platforms" asp-action="Index" class="btn btn-warning offset-1 col-2 rounded-pill">View All Platforms</a>
                <a asp-area="Administration" asp-controller="Languages" asp-action="Index" class="btn btn-warning offset-1 col-2 rounded-pill">View All Languages</a>
                <a asp-area="Administration" asp-controller="Countries" asp-action="Index" class="btn btn-warning offset-1 col-2 rounded-pill">View All Countries</a>
            </div>
        </p>
        <p class="lead">
            <h4 class="mb-3">| Update:</h4>
            <div class="row mb-4">
                <form asp-area="Administration" asp-controller="Movies" asp-action="Edit" method="get" class="mb-3">
                    <input name="Id" type="number" placeholder="Enter target movie Id" class="col-2">
                    <input type="submit" class="btn btn-warning col-2 rounded-pill" value="Edit Movie">
                </form>
                <form asp-area="Administration" asp-controller="Actors" asp-action="Edit" method="get" class="mb-3">
                    <input name="Id" type="number" placeholder="Enter target actor Id" class="col-2">
                    <input type="submit" class="btn btn-warning col-2 rounded-pill" value="Edit Actor">
                </form>
                <form asp-area="Administration" asp-controller="Genres" asp-action="Edit" method="get" class="mb-3">
                    <input name="Id" type="number" placeholder="Enter target genre Id" class="col-2">
                    <input type="submit" class="btn btn-warning col-2 rounded-pill" value="Edit Genre">
                </form>
                <form asp-area="Administration" asp-controller="Images" asp-action="Edit" method="get" class="mb-3">
                    <input name="Id" type="number" placeholder="Enter target image Id" class="col-2">
                    <input type="submit" class="btn btn-warning col-2 rounded-pill" value="Edit Image">
                </form>
                <form asp-area="Administration" asp-controller="Directors" asp-action="Edit" method="get" class="mb-3">
                    <input name="Id" type="number" placeholder="Enter target director Id" class="col-2">
                    <input type="submit" class="btn btn-warning col-2 rounded-pill" value="Edit Director">
                </form>
                <form asp-area="Administration" asp-controller="Platforms" asp-action="Edit" method="get" class="mb-3">
                    <input name="Id" type="number" placeholder="Enter target platform Id" class="col-2">
                    <input type="submit" class="btn btn-warning col-2 rounded-pill" value="Edit Platform">
                </form>
                <form asp-area="Administration" asp-controller="Languages" asp-action="Edit" method="get" class="mb-3">
                    <input name="Id" type="number" placeholder="Enter target language Id" class="col-2">
                    <input type="submit" class="btn btn-warning col-2 rounded-pill" value="Edit Language">
                </form>
                <form asp-area="Administration" asp-controller="Countries" asp-action="Edit" method="get" class="mb-3">
                    <input name="Id" type="number" placeholder="Enter target country Id" class="col-2">
                    <input type="submit" class="btn btn-warning col-2 rounded-pill" value="Edit Country">
                </form>
            </div>
        </p>
        <p class="lead">
            <h4 class="mb-3">| Delete:</h4>
            <div class="row mb-4">
                <form asp-area="Administration" asp-controller="Movies" asp-action="Delete" method="get" class="mb-3">
                    <input name="Id" type="number" placeholder="Enter target movie Id" class="col-2">
                    <input type="submit" class="btn btn-warning col-2 rounded-pill" value="Delete Movie">
                </form>
                <form asp-area="Administration" asp-controller="Actors" asp-action="Delete" method="get" class="mb-3">
                    <input name="Id" type="number" placeholder="Enter target actor Id" class="col-2">
                    <input type="submit" class="btn btn-warning col-2 rounded-pill" value="Delete Actor">
                </form>
                <form asp-area="Administration" asp-controller="Genres" asp-action="Delete" method="get" class="mb-3">
                    <input name="Id" type="number" placeholder="Enter target genre Id" class="col-2">
                    <input type="submit" class="btn btn-warning col-2 rounded-pill" value="Delete Genre">
                </form>
                <form asp-area="Administration" asp-controller="Images" asp-action="Delete" method="get" class="mb-3">
                    <input name="Id" type="number" placeholder="Enter target image Id" class="col-2">
                    <input type="submit" class="btn btn-warning col-2 rounded-pill" value="Delete Image">
                </form>
                <form asp-area="Administration" asp-controller="Directors" asp-action="Delete" method="get" class="mb-3">
                    <input name="Id" type="number" placeholder="Enter target director Id" class="col-2">
                    <input type="submit" class="btn btn-warning col-2 rounded-pill" value="Delete Director">
                </form>
                <form asp-area="Administration" asp-controller="Platforms" asp-action="Delete" method="get" class="mb-3">
                    <input name="Id" type="number" placeholder="Enter target platform Id" class="col-2">
                    <input type="submit" class="btn btn-warning col-2 rounded-pill" value="Delete Platform">
                </form>
                <form asp-area="Administration" asp-controller="Languages" asp-action="Delete" method="get" class="mb-3">
                    <input name="Id" type="number" placeholder="Enter target language Id" class="col-2">
                    <input type="submit" class="btn btn-warning col-2 rounded-pill" value="Delete Language">
                </form>
                <form asp-area="Administration" asp-controller="Countries" asp-action="Delete" method="get" class="mb-3">
                    <input name="Id" type="number" placeholder="Enter target country Id" class="col-2">
                    <input type="submit" class="btn btn-warning col-2 rounded-pill" value="Delete Country">
                </form>
            </div>
        </p>
    </div>
    <div class="mt-5">
        <center><h3> Forum System for Application</h3></center>
        <hr class="offset-2 col-8">
        <p class="lead">
            <h4 class="mb-3">| Create:</h4>
            <div class="row mb-5">
                <a asp-area="Administration" asp-controller="Posts" asp-action="Create" class="btn btn-warning col-2 rounded-pill">Post</a>
                <a asp-area="Administration" asp-controller="Comments" asp-action="Create" class="btn btn-warning offset-1 col-2 rounded-pill">Create Comment</a>
            </div>
        </p>
        <p class="lead">
            <h4 class="mb-3">| Read:</h4>
            <div class="row mb-5">
                <a asp-area="Administration" asp-controller="Posts" asp-action="Index" class="btn btn-warning col-2 rounded-pill">Post</a>
                <a asp-area="Administration" asp-controller="Comments" asp-action="Index" class="btn btn-warning offset-1 col-2 rounded-pill">Create Comment</a>
            </div>
        </p>
        <p class="lead">
            <h4 class="mb-3">| Update:</h4>
            <div class="row mb-5">
                <form asp-area="Administration" asp-controller="Posts" asp-action="Edit" method="get" class="mb-3">
                    <input name="Id" type="number" placeholder="Enter target post Id" class="col-2">
                    <input type="submit" class="btn btn-warning col-2 rounded-pill" value="Edit Post">
                </form>
                <form asp-area="Administration" asp-controller="Comments" asp-action="Edit" method="get" class="mb-3">
                    <input name="Id" type="number" placeholder="Enter target comment Id" class="col-2">
                    <input type="submit" class="btn btn-warning col-2 rounded-pill" value="Edit Comment">
                </form>
            </div>
        </p>
        <p class="lead">
            <h4 class="mb-3">| Delete:</h4>
            <div class="row mb-5">
                <form asp-area="Administration" asp-controller="Posts" asp-action="Delete" method="get" class="mb-3">
                    <input name="Id" type="number" placeholder="Enter target post Id" class="col-2">
                    <input type="submit" class="btn btn-warning col-2 rounded-pill" value="Delete Post">
                </form>
                <form asp-area="Administration" asp-controller="Comments" asp-action="Delete" method="get" class="mb-3">
                    <input name="Id" type="number" placeholder="Enter target comment Id" class="col-2">
                    <input type="submit" class="btn btn-warning col-2 rounded-pill" value="Delete Comment">
                </form>
            </div>
        </p>
    </div>
    <div class="mt-5">
        <hr>
        <center><h3 class="mb-5">Custom administartion logic</h3></center>
        <form asp-area="" asp-controller="Movies" asp-action="Details" method="get" class="mb-3">
            <input name="Name" class="col-2 border-warning" type="text" placeholder="Serach movie by name">
            <input type="submit" class="btn btn-warning btn-sm rounded-pill" style="margin-left:20px" value="Go">
        </form>
        <form asp-area="" asp-controller="Movies" asp-action="EditIndex" method="get" class="mb-3">
            <input name="Name" class="col-2 border-warning" type="text" placeholder="Edit movie by name">
            <input type="submit" class="btn btn-warning btn-sm rounded-pill" style="margin-left:20px" value="Go">
        </form>
        <form asp-area="" asp-controller="Movies" asp-action="DeleteConfirmation" method="get" class="mb-3">
            <input name="Name" class="col-2 border-warning" type="text" placeholder="Delete movie by name">
            <input type="submit" class="btn btn-warning btn-sm rounded-pill" style="margin-left:20px" value="Go">
        </form>
        <a asp-area="" asp-controller="Movies" asp-action="Create" class=" btn btn-warning btn-sum rounded-pill mb-1" role="button">Create Movie</a>
    </div>
</div>